### ISSUE TITLE
1. Copy value doesn't work. 2. Code folding doesn't work

### ISSUE THREAD

**Issue by wzup** [teocci/JSONViewer-for-Chrome#4]
1. Copy value doesn't work. 

2. Code folding doesn't work

How to enable?

**Comment by teocci** [comment]
Are you using this version https://goo.gl/QWWes1?
The last version has all the features working the only feature that doesn't
work is the View Original Code because google has blocked that feature. Now
I'm try to think how to show it again.

*Teocci*
*Programmer & Web App Developer*
*99 Daehak-Ro, Yuseong-Gu, Daejeon, 305-764, South Korea*
*E-mail **:** jrfdeft@gmail.com <jrfdeft@gmail.com>*
